#!/usr/bin/python

# (C) Copyright 2006 Nuxeo SAS <http://nuxeo.com>
# Author: bdelbosc@nuxeo.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
"""Product man program

$Id: bm-product 49072 2006-08-23 15:22:43Z bdelbosc $
"""
import sys
from bundleman.productman import ProductManProgram

def main():
    """main."""
    prog = ProductManProgram()
    ret = prog.run()
    sys.exit(ret)

if __name__ == '__main__':
    main()
