# BundleMan Makefile
# $Id: Makefile 49061 2006-08-23 12:38:41Z bdelbosc $
#
.PHONY: clean


clean:
	find . "(" -name "*~" -or  -name ".#*" -or  -name "#*#" -or -name "*.pyc" ")" -print0 | xargs -0 rm -f

